/**
 * 
 */
package com.github.nest.arcteryx.meta.beans.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * bean property annotation. Name of property will be auto generated by method
 * or field which is annotated.
 * 
 * @author brad.wu
 */
@Target({ ElementType.METHOD, ElementType.FIELD })
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface ArcteryxBeanProperty {
	/**
	 * description of property, optional
	 * 
	 * @return
	 */
	String description() default "";
}
