DROP TABLE T_PARTY IF EXISTS;
CREATE TABLE T_PARTY (
	-- PARTY 
	PARTY_ID BIGINT PRIMARY KEY,
	PARTY_TYPE_CODE VARCHAR(1) NOT NULL,
	ID_NUMBER VARCHAR(20) NOT NULL,
	IS_ENABLED BOOLEAN,
	PARTY_NAME VARCHAR(90) NOT NULL,
	-- COMMON
	DATE_OF_BIRTH DATE,
	DATE_OF_DEATH DATE,
	ID_TYPE_CODE VARCHAR(2),
	-- INDIVIDUAL
	ALIAS_NAME VARCHAR(30),
	COUNTRY_CODE_OF_BIRTH VARCHAR(3),
	COURTESY_TITLE VARCHAR(10),
	FIRST_NAME VARCHAR(30),
	MIDDLE_NAME VARCHAR(30),
	LAST_NAME VARCHAR(30),
	GENDER_CODE VARCHAR(1),
	MARITAL_CODE VARCHAR(1),
	NATIONALITY_CODE VARCHAR(3),
	OCCUPATION_CODE VARCHAR(3),
	RACE_CODE VARCHAR(1),
	RELIGION_CODE VARCHAR(2),
	-- ORGANIZATION
	ORGANIZATION_NAME VARCHAR(50),
	LEGAL_REPRESENTATIVE VARCHAR(30),
	LEGAL_TYPE_CODE VARCHAR(2),
	-- AUDIT
	CREATED_BY BIGINT, 
	CREATED_DATE DATETIME, 
	LAST_MODIFIED_BY BIGINT, 
	LAST_MODIFIED_DATE DATETIME,
	-- VERSIONING
	OPT_LOCK BIGINT
);

DROP SEQUENCE S_PARTY IF EXISTS;
CREATE SEQUENCE S_PARTY;