DROP TABLE T_UT_TABLE IF EXISTS;
CREATE TABLE T_UT_TABLE (
	UT_ID BIGINT, 
	UT_NAME VARCHAR(30), 
	CREATED_BY BIGINT, 
	CREATED_DATE DATETIME, 
	LAST_MODIFIED_BY BIGINT, 
	LAST_MODIFIED_DATE DATETIME
);

DROP SEQUENCE S_UT_TABLE IF EXISTS;
CREATE SEQUENCE S_UT_TABLE;
