INSERT INTO T_PARTY (PARTY_ID, PARTY_TYPE_CODE, ID_NUMBER, PARTY_NAME)
	VALUES (1, 'I', 'I00001', 'JOHN DOE');
INSERT INTO T_PARTY (PARTY_ID, PARTY_TYPE_CODE, ID_NUMBER, PARTY_NAME)
	VALUES (2, 'O', 'O00001', 'Oracle');
	
INSERT INTO T_PARTY_ADDRESS (ADDRESS_ID, COUNTRY_CODE, PARTY_ID)
	VALUES (1, 'CHN', 2);
